#!/bin/sh

set -e

[ -z "${DAEMON_URLS}" ] && DAEMON_URLS="ldap://"

schema_dir="/etc/openldap/schema"
config_file="/etc/openldap/slapd.conf"
config_dir="/etc/openldap/slapd.d/"

data_dir="/var/lib/openldap-data"
run_dir="/var/run/openldap"

ldap_user="ldap"
ldap_group="ldap"

run_server() {
	mkdir -p "${run_dir}"

	chown -R ${ldap_user}:${ldap_group} "${data_dir}"
	chown -R ${ldap_user}:${ldap_group} "${run_dir}"

	if [ -d "${config_dir}" ]; then
		chown -R ${ldap_user}:${ldap_group} "${config_dir}"
	fi

	chmod 0700 "${data_dir}"

	# -d level	Debug level
	# -f filename	Configuration file
	# -F dir	Configuration directory

	args="-h ${DAEMON_URLS} -u ${ldap_group} -g ${ldap_user}"

	if [ -f "${config_file}" ]; then
		args="${args} -f ${config_file}"

	elif [ -d "${config_dir}" ]; then
		# http://www.openldap.org/doc/admin24/slapdconf2.html
		args="${args} -f ${config_file} -F ${config_dir}"
	fi

	args="${args} -d stats $*"

	# See bug https://github.com/docker/docker/issues/8231
	ulimit -n 1024

	exec /usr/sbin/slapd ${args}
}

setup() {
	if [ -f "${config_file}" -o -d "${config_dir}" ]; then
		return
	fi

	cat > "${config_file}" << EOF
#
# etc/openldap/slapd.conf
#

# This file was automatically generated by $0

include		${schema_dir}/core.schema
include		${schema_dir}/cosine.schema
include		${schema_dir}/inetorgperson.schema
include		${schema_dir}/openldap.schema
include		${schema_dir}/misc.schema
include		${schema_dir}/nis.schema

pidfile		${run_dir}/slapd.pid
argsfile	${run_dir}/slapd.args

# Load dynamic backend modules:
modulepath	/usr/lib/openldap
#moduleload	back_sock.so
#moduleload	back_shell.so
#moduleload	back_relay.so
#moduleload	back_passwd.so
#moduleload	back_null.so
#moduleload	back_monitor.so
#moduleload	back_meta.so
#moduleload	back_ldap.so
#moduleload	back_dnssrv.so

# Sample security restrictions
#	Require integrity protection (prevent hijacking)
#	Require 112-bit (3DES or better) encryption for updates
#	Require 63-bit encryption for simple bind
#security ssf=1 update_ssf=112 simple_bind=64

# Sample access control policy:
access to dn.base="" by * read
access to dn.base="cn=Subschema" by * read
access to attrs=userPassword
	by self write
	by anonymous auth
	by * none
access to *
	by self write
	by users read
	by anonymous read

loglevel 0

database	hdb
suffix		"dc=example,dc=com"
checkpoint	32	30 
rootdn		"cn=Manager,dc=example,dc=com"
rootpw		"secret"
# The database directory MUST exist prior to running slapd AND 
# should only be accessible by the slapd and slap tools.
# Mode 700 recommended.
directory	${data_dir}/example.com
# Indices to maintain
index	objectClass	eq
index	entryCSN	eq
index	entryUUID	eq
index	cn		eq
index	mail		eq
index	uid		eq

#overlay                 syncprov
#syncprov-checkpoint     100 10
#syncprov-sessionlog     100

#syncrepl rid=001
#	provider="ldap://ldap.example.com"
#	searchbase="dc=example,dc=com"
#	scope=sub
#	type=refreshAndPersist
#	retry="15 8 60 10 300 +"
#	interval="00:00:10:07"
#	bindmethod="simple"
#	binddn="cn=syncer,dc=example,dc=com"
#	credentials="secret"

EOF

	if [ ! -f ${data_dir}/example.com ]; then
		mkdir -p ${data_dir}/example.com
		chmod 0700 ${data_dir}/example.com
	fi

	if [ ! -d ${schema_dir} ]; then
		cp -a /etc/openldap.default/schema ${schema_dir}
	fi

	if [ ! -f /etc/openldap/ldap.conf ]; then
		cat > /etc/openldap/ldap.conf << EOF
#
# etc/openldap/ldap.conf
#

# This file was automatically generated by $0

uri	ldap://localhost
base	dc=example,dc=com

#SIZELIMIT	12
#TIMELIMIT	15
#DEREF		never

EOF
	fi
}

case "$1" in
serve|server)
	shift
	setup
	run_server
	;;

setup)
	shift
	setup
	exit 0
	;;

shell)
	shift
	exec $*
	;;

*)
	exec $*
	;;
esac

