#!/bin/sh

set -e

case "$1" in
	server)
		shift
		;;

	*)
		exec $*
		;;
esac

[ -z "${DAEMON_URLS}" ] && DAEMON_URLS="ldap://"

config_file="/etc/openldap/slapd.conf"
config_dir="/etc/openldap/slapd.d/"

data_dir="/var/lib/openldap-data"
run_dir="/var/run/openldap"

openldap_user="ldap"
openldap_group="ldap"

if [ ! -f "${config_file}" -a ! -f "${config_dir}" ]; then
	cat > "${config_file}" << EOF
#
# etc/openldap/slapd.conf
#

# This file was automatically generated by $0

include		/etc/openldap/schema/core.schema
include		/etc/openldap/schema/cosine.schema
include		/etc/openldap/schema/inetorgperson.schema
include		/etc/openldap/schema/openldap.schema
include		/etc/openldap/schema/misc.schema
include		/etc/openldap/schema/nis.schema

pidfile		/var/run/openldap/slapd.pid
argsfile	/var/run/openldap/slapd.args

# Load dynamic backend modules:
modulepath	/usr/lib/openldap
#moduleload	back_sock.so
#moduleload	back_shell.so
#moduleload	back_relay.so
#moduleload	back_passwd.so
#moduleload	back_null.so
#moduleload	back_monitor.so
#moduleload	back_meta.so
#moduleload	back_ldap.so
#moduleload	back_dnssrv.so

# Sample security restrictions
#	Require integrity protection (prevent hijacking)
#	Require 112-bit (3DES or better) encryption for updates
#	Require 63-bit encryption for simple bind
#security ssf=1 update_ssf=112 simple_bind=64

# Sample access control policy:
access to dn.base="" by * read
access to dn.base="cn=Subschema" by * read
access to attrs=userPassword
	by self write
	by anonymous auth
	by * none
access to *
	by self write
	by users read
	by anonymous read

loglevel 0

database	hdb
suffix		"dc=example,dc=com"
checkpoint	32	30 
rootdn		"cn=Manager,dc=example,dc=com"
rootpw		"secret"
# The database directory MUST exist prior to running slapd AND 
# should only be accessible by the slapd and slap tools.
# Mode 700 recommended.
directory	/var/lib/openldap-data/example.com
# Indices to maintain
index	objectClass	eq
index	entryCSN	eq
index	entryUUID	eq
index	cn		eq
index	mail		eq
index	uid		eq

#overlay                 syncprov
#syncprov-checkpoint     100 10
#syncprov-sessionlog     100

#syncrepl rid=001
#	provider="ldap://ldap.example.com"
#	searchbase="dc=example,dc=com"
#	scope=sub
#	type=refreshAndPersist
#	retry="15 8 60 10 300 +"
#	interval="00:00:10:07"
#	bindmethod="simple"
#	binddn="cn=syncer,dc=example,dc=com"
#	credentials="secret"

EOF

	if [ ! -f /var/lib/openldap-data/example.com ]; then
		mkdir -p /var/lib/openldap-data/example.com
		chmod 0700 /var/lib/openldap-data/example.com
	fi

	if [ ! -d /etc/openldap/schema/ ]; then
		cp -a /etc/openldap.default/schema /etc/openldap/schema
	fi

	if [ ! -f /etc/openldap/ldap.conf ]; then
		cat > /etc/openldap/ldap.conf << EOF
#
# etc/openldap/ldap.conf
#

# This file was automatically generated by $0

uri	ldap://localhost
base	dc=example,dc=com

#SIZELIMIT	12
#TIMELIMIT	15
#DEREF		never

EOF
	fi
fi

mkdir -p "${run_dir}"

chown -R ${openldap_user}:${openldap_group} "${data_dir}"
chown -R ${openldap_user}:${openldap_group} "${run_dir}"

chmod 0700 "${data_dir}"

# -d level	Debug level
# -f filename	Configuration file
# -F dir	Configuration directory

args="-u ${openldap_group} -g ${openldap_user}"

if [ -f "${config_file}" ]; then
	args="${args} -f ${config_file}"
elif [ -d "${config_dir}" ]; then
	args="${args} -F ${config_dir}"
fi

args="${args} -d 0"

exec /usr/sbin/slapd -h "${DAEMON_URLS}" ${args}
